version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - mkevenaar
  assignees:
  - mkevenaar
  labels:
  - dependabot
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - mkevenaar
  assignees:
  - mkevenaar
  labels:
  - dependabot
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - mkevenaar
  assignees:
  - mkevenaar
  labels:
  - dependabot
