name: Node.js CI

on:
  push:
    branches: [develop, main]
  pull_request:

jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
      - run: yarn run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.6.0
