name: Node.js CI

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
      - run: yarn run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
